//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace Escc.Cms.WebServices.CmsResourcesProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ResourcesSoap", Namespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices")]
    public partial class Resources : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RootResourceGalleryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResourceGalleryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Resources() {
            this.Url = global::Escc.Cms.WebServices.Properties.Settings.Default.Escc_Cms_WebServices_CmsResourcesProxy_Resources;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RootResourceGalleryCompletedEventHandler RootResourceGalleryCompleted;
        
        /// <remarks/>
        public event ResourceGalleryCompletedEventHandler ResourceGalleryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/Escc.Cms.WebServices/RootResourceGallery", RequestNamespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices", ResponseNamespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CmsResourceGallery RootResourceGallery() {
            object[] results = this.Invoke("RootResourceGallery", new object[0]);
            return ((CmsResourceGallery)(results[0]));
        }
        
        /// <remarks/>
        public void RootResourceGalleryAsync() {
            this.RootResourceGalleryAsync(null);
        }
        
        /// <remarks/>
        public void RootResourceGalleryAsync(object userState) {
            if ((this.RootResourceGalleryOperationCompleted == null)) {
                this.RootResourceGalleryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRootResourceGalleryOperationCompleted);
            }
            this.InvokeAsync("RootResourceGallery", new object[0], this.RootResourceGalleryOperationCompleted, userState);
        }
        
        private void OnRootResourceGalleryOperationCompleted(object arg) {
            if ((this.RootResourceGalleryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RootResourceGalleryCompleted(this, new RootResourceGalleryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/Escc.Cms.WebServices/ResourceGallery", RequestNamespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices", ResponseNamespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CmsResourceGallery ResourceGallery(System.Guid guid) {
            object[] results = this.Invoke("ResourceGallery", new object[] {
                        guid});
            return ((CmsResourceGallery)(results[0]));
        }
        
        /// <remarks/>
        public void ResourceGalleryAsync(System.Guid guid) {
            this.ResourceGalleryAsync(guid, null);
        }
        
        /// <remarks/>
        public void ResourceGalleryAsync(System.Guid guid, object userState) {
            if ((this.ResourceGalleryOperationCompleted == null)) {
                this.ResourceGalleryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResourceGalleryOperationCompleted);
            }
            this.InvokeAsync("ResourceGallery", new object[] {
                        guid}, this.ResourceGalleryOperationCompleted, userState);
        }
        
        private void OnResourceGalleryOperationCompleted(object arg) {
            if ((this.ResourceGalleryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResourceGalleryCompleted(this, new ResourceGalleryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices")]
    public partial class CmsResourceGallery {
        
        private System.Guid guidField;
        
        private string nameField;
        
        private string pathField;
        
        private CmsResourceGallery[] galleriesField;
        
        private CmsResource[] resourcesField;
        
        /// <remarks/>
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public CmsResourceGallery[] Galleries {
            get {
                return this.galleriesField;
            }
            set {
                this.galleriesField = value;
            }
        }
        
        /// <remarks/>
        public CmsResource[] Resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices")]
    public partial class CmsResource {
        
        private System.Guid guidField;
        
        private string nameField;
        
        private string displayNameField;
        
        private string pathField;
        
        /// <remarks/>
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RootResourceGalleryCompletedEventHandler(object sender, RootResourceGalleryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RootResourceGalleryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RootResourceGalleryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CmsResourceGallery Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CmsResourceGallery)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ResourceGalleryCompletedEventHandler(object sender, ResourceGalleryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResourceGalleryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResourceGalleryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CmsResourceGallery Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CmsResourceGallery)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591